### ISSUE TITLE
Fix conflicts with templating and ecmascript

### ISSUE THREAD

**Issue by jperl** [timbrandin/sideburns#24]
This package is really amazing, thank you for putting it together. I really wish I could use it!

It would be nice if this package could co-exist with `templating` & `ecmascript` -- for those migrating to react. The only way I can think of this is by renaming the file extensions.

![](https://s3.amazonaws.com/f.cl.ly/items/263k0L302q1Q0r1V0K1G/Screen%20Shot%202015-11-03%20at%2010.16.30%20AM.png)

**Comment by jperl** [comment]
It works if you isolate components into a separate package. So I guess this is not that important.

**Comment by timbrandin** [comment]
yeah, I haven't documented that one doesn't need the ecmascript package, react-templates takes care of that because we need to find the events before the html transpiler starts working to be able to add it in the template.

React likes when you specify the events in the markup, which differs from Blaze.

**Comment by timbrandin** [comment]
so to solve this: remove `blaze-html-templates` and `ecmascript`
